# Generated by Django 4.1.3 on 2022-11-13 11:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('tconst', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('titleType', models.CharField(max_length=32)),
                ('primaryTitle', models.CharField(max_length=256)),
                ('originalTitle', models.CharField(max_length=256)),
                ('startYear', models.IntegerField()),
                ('endYear', models.IntegerField()),
                ('runtimeMinutes', models.IntegerField()),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('tconst', models.OneToOneField(max_length=9, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='imdb.title')),
                ('averageRating', models.FloatField()),
                ('numVotes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('tconst', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('seasonNumber', models.IntegerField()),
                ('episodeNumber', models.IntegerField()),
                ('parentTconst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.title')),
            ],
        ),
    ]
