# Generated by Django 4.1.3 on 2022-11-22 20:14

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "tconst",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("titleType", models.CharField(max_length=32)),
                ("primaryTitle", models.CharField(max_length=1024)),
                ("originalTitle", models.CharField(max_length=1024)),
                ("isAdult", models.BooleanField(blank=True, null=True)),
                ("startYear", models.IntegerField(blank=True, null=True)),
                ("endYear", models.IntegerField(blank=True, default=None, null=True)),
                ("runtimeMinutes", models.IntegerField(blank=True, null=True)),
                (
                    "genres",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "tconst",
                    models.OneToOneField(
                        max_length=32,
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="imdb.title",
                    ),
                ),
                ("averageRating", models.FloatField()),
                ("numVotes", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "tconst",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("seasonNumber", models.IntegerField(blank=True, null=True)),
                ("episodeNumber", models.IntegerField(blank=True, null=True)),
                (
                    "parentTconst",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="imdb.title",
                    ),
                ),
            ],
        ),
    ]
