version: '3.9'

services:
  frontend:
    restart: always
    build:
      dockerfile: Dockerfile.prod
  backend:
    restart: always
    build:
      dockerfile: Dockerfile.prod
    environment:
      - DEBUG=False
  db:
    restart: always

networks:
  default:
    name: ${PROXY_NETWORK}
    external: True
