version: '3.9'

services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./backend:/django
    environment:
      - DEBUG=True
    command: [
        './wait-for-it.sh',
        'db:5432',
        '--',
        'bash',
        '-c',
        'python manage.py makemigrations imdb;
        python manage.py migrate;
        python manage.py runserver 0.0.0.0:8000',
      ]
