version: '3.9'

services:
  # frontend:
  #   image: node:19.2-alpine
  #   container_name: frontend
  #   ports:
  #     - 3000:3000
  #   command: npm start
  backend:
    container_name: backend
    build: ./backend/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backend:/django:rw
      - /tmp/imdb_datasets:/tmp/imdb_datasets:rw
    working_dir: /django
    command: [
        './wait-for-it.sh',
        'db:5432',
        '--',
        'bash',
        '-c',
        'python3 manage.py makemigrations;
        python3 manage.py migrate;
        python manage.py runserver 0.0.0.0:8000',
      ]
  db:
    container_name: postgres
    image: postgres:latest
    shm_size: 1g
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
