version: '3.9'

services:
  frontend:
    container_name: tvratings-frontend
    hostname: tvratings-frontend
    build:
      context: ./frontend
    deploy:
      resources:
        limits:
          memory: ${REACT_MEM_LIMIT}
          cpus: '${REACT_CPU_LIMIT}'
  backend:
    container_name: tvratings-api
    hostname: tvratings-api
    build:
      context: ./backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - /tmp/imdb_datasets:/tmp/imdb_datasets:rw
    deploy:
      resources:
        limits:
          memory: ${DJANGO_MEM_LIMIT}
          cpus: '${DJANGO_CPU_LIMIT}'
  db:
    container_name: tvratings-db
    image: postgres:15.4-bookworm
    env_file:
      - .env
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'imdb']
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 60s
    shm_size: ${POSTGRES_SHM_SIZE}
    deploy:
      resources:
        limits:
          memory: ${POSTGRES_MEM_LIMIT}
          cpus: '${POSTGRES_CPU_LIMIT}'

volumes:
  postgres_data:
