FROM python:3

ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /django

COPY ./requirements.txt .
RUN pip install -r requirements.txt

RUN mkdir -pv /var/log/gunicorn/
RUN mkdir -pv /var/run/gunicorn/

COPY . .
EXPOSE 8000

CMD [ "gunicorn", "-c", "config/gunicorn/prod.py" ]